name = "GraphMatrices"
uuid = "195e1e3a-597a-4369-afc5-1df015e183c4"
authors = ["Gideon Simpson <gideon.simpson@gmail.com>"]
version = "0.1.0"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
